---
version: "3.0"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'ensinosuperior'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:      
      - ../sql.init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 3
      start_period: 5s
  openjdk:
    hostname: openjdk
    image: openjdk:oraclelinux8
    container_name: openjdk
    volumes:
      - ../bin:/usr/src/DataAgregator
    working_dir: /usr/src/DataAgregator
    command: java -jar DataAggregator-1.0.jar    
    depends_on:
      mysql:
        condition: service_healthy
volumes:  
  mysqldata:
    driver: local